### ISSUE TITLE
How to learn more about the project?

### ISSUE THREAD

**Issue by 3devilscapital** [violinio/violin-docs#1]
Hey! @ImmodestExtant @musecrypto 
We're super interested to see this new project made by RugDoc, It makes a lot of sense.
How can we learn more about the project? Can we join a Discord or a Telegram group to discuss with the team?
Thank you!

**Comment by ImmodestExtant** [comment]
Hi, you can reach out in our telegram group for partnerships, etc. We will announce more project details in the future. https://t.me/RugDocChat
